version: '3'

services:
#  web:
#    build: .
#    ports:
#      - "5000:5000"
#    depends_on:
#      - db
#    environment:
#      DATABASE_URL: "postgresql://postgres:postgres@localhost:15432/stacaccessibility_db"
#      FLASK_ENV: development
#    volumes:
#      - .:/app
  db:
    image: postgis/postgis:16-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stacaccessibility_db
    ports:
      - "15432:5432"
