version: "3"

services:
  # web:
  #   build: .
  #   ports:
  #     - "5005:5005"
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_HOST: "db"
  #     DATABASE_PORT: "5432"
  #     DATABASE_NAME: "stacaccessibility_db"
  #     DATABASE_USER: "postgres"
  #     DATABASE_PASSWORD: "postgres"
  #     APP_HOST: "0.0.0.0"
  #     APP_PORT: "5005"
  #     APP_DEBUG: "True"
  #   volumes:
  #     - .:/app

  scrape:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "stacaccessibility_db"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
      APP_HOST: "0.0.0.0"
      APP_PORT: "5000"
      APP_DEBUG: "True"
    command: ["python", "scrape.py"]

  dbinit:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "stacaccessibility_db"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
      APP_HOST: "0.0.0.0"
      APP_PORT: "5000"
      APP_DEBUG: "True"
    command: ["/bin/sh", "-c", "sleep 5 && python database.py"]

  db:
    image: postgis/postgis:16-master
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "stacaccessibility_db"
    ports:
      - "15432:5432"

  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "postgres"
  #     POSTGRES_DB: "stacaccessibility_db"
  #   ports:
  #     - "15432:5432"
  
